#
# SPDX-FileCopyrightText: 2011-2025 EasyCoding Team
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
